# font_family Fira Code
font_size 11

# BEGIN_KITTY_THEME
Night Lion V1
include current-theme.conf
# END_KITTY_THEME

cursor_shape block


# BEGIN_KITTY_FONTS
font_family      family="FiraCode Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

cursor_shape          beam
cursor_blink_interval -1

# [window]
# set-title-format = "{window_title} -- kitty"
enable_audio_bell = no
confirm_os_window_close 0
window_padding_width 4
