theme = "onedark"

[editor]
# line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
ins = "insert_mode"
esc = ["collapse_selection", "keep_primary_selection"]
C-o = ":config-open" # Maps Ctrl-o to opening of the helix config file
C-r = ":config-reload"
C-s = ":w"
C-z = "undo"
C-Z = "redo"
S-z = ":q"
